model_name_or_path: /your_path/Qwen2.5-7B-Instruct
stage: dpo
do_train: true
do_eval: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json
pref_beta: 1.5
pref_loss: sigmoid
dataset: qwen_mpo_data
template: qwen
cutoff_len: 1024
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
output_dir: saves/qwen2.5-7b/your_path
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 6.0e-07
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
save_only_model: true
save_strategy: 'no'

### Uncomment below to publish the trained model to Hugging Face Hub
# publish_to_hf: true
# hf_hub_model_id: your_username/qwen2.5-7b-mpo
# hf_hub_private: false
# hf_hub_token: your_hf_token
